Azure/azure-iot-sdk-python

device/samples/iothub_client_sample.py

The sample code has the option to set a message property but it is never assigned to the message. This code will assign the prop_map to the message properties.

Set message properties

---

build_all/mac/build.sh
build_all/mac/release.sh
build_all/mac/release_device_client/build/lib.linux-x86_64-2.7/iothub_client/__init__.py
build_all/mac/release_device_client/build/lib/iothub_client/__init__.py
build_all/mac/release_device_client/iothub_client/__init__.py
build_all/mac/release_device_client/setup_device_client.py
build_all/mac/release_service_client/build/lib.linux-x86_64-2.7/iothub_service_client/__init__.py
build_all/mac/release_service_client/build/lib/iothub_service_client/__init__.py
build_all/mac/release_service_client/iothub_service_client/__init__.py
build_all/mac/release_service_client/setup_service_client.py
build_all/mac/setup.sh
device/iothub_client_python/CMakeLists.txt
doc/python-devbox-setup.md
service/CMakeLists.txt

Python module does not build on Mac OS
I copied the linux version, and changed the parameters to work on Mac OS.

build Python Module on Mac OS

---

build_all/mac/setup.sh

Unlike setup scripts for linux and windows (and in the documentation), the command line argument for the python version was --build-python instead of --python-version.
Changed the command line argument to --python-version.

Argname --python-version to reflect other builds/readme

---

service/src/iothub_service_client_python.cpp

- [x ] I have read the [contribution guidelines] (https://github.com/Azure/azure-iot-sdk-python/blob/master/.github/CONTRIBUTING.md).
- [N/A ] I added or modified the existing tests to cover the change (we do not allow our test coverage to go down).
- [N/A ] I edited the corresponding document in the `devdoc` folder and added or modified requirements.
- [N/A] This pull-request is submitted against the `master` branch. 
The use of initializing non-static member variables in classes is not supported by older compilers. This is causing compatibility problems with certain Linux distributions.
Removed all non-static member inline initialization and added them to the …

Mods to allow older compilers to build code

---

service/src/iothub_service_client_python.cpp

- [Y ] I have read the [contribution guidelines] (https://github.com/Azure/azure-iot-sdk-python/blob/master/.github/CONTRIBUTING.md).
- [ N/A] I added or modified the existing tests to cover the change (we do not allow our test coverage to go down).
Initialization of non-static class member variables is unsupported by older versions of g++.
Variables are now initialized in the constructor.

Change for compatibility with older compilers

---

doc/python-devbox-setup.md

Error where pip install will return 'Could not find a version that satisfies the requirements...'. A fix is to specify pip3, as it seems to only work with Python 3+
- I submitted this PR against the correct branch:

Addition to pip install notes for raspberry devices

---

build_all/mac/release.sh

Issue #135
Wheels built for MacOSX can't be installed on MacOSX.
This is similar to issue #36 -- the PLAT_ARCH is embedded
as a tag in the wheel name. But as far as I can tell,
macos64 and macos32 are not supported platforms on any machine.
Update the two PLAT_ARCH tags to macosx_10_6_x86_64 and macosx_10_6_i386
$ python --version
Python 3.6.5
$ azure-iot-sdk-python/build_all/mac/release.sh --build-python 3.6
$ pip install azure-iot-sdk-python/build_all/mac/release_service_client/dist/azure_iothub_service_client-1.3.2-py3-none-macosx_10_6_x86_64.whl
Processing ./release_service_client/dist/azure_iothub_service_client-1.3.2-py3-none-macosx_10_6_x86_64.whl
Installing …

Fix #135 - Mac: not a supported wheel on this platform

---

build_all/mac/setup.sh

- [X ] I have read the [contribution guidelines] (https://github.com/Azure/azure-iot-sdk-python/blob/master/.github/CONTRIBUTING.md).
Original text stated that it only supported up to 3.5, but if statement was covering to 3.6.
Just adding that 3.6 is supported.

Adding notice that 3.6 is also supported

---

device/samples/iothub_client_simple_sample.py
device/tests/iothub_client_e2e.py

- [x ] I have squashed my changes into one with a clear description of the change.
I have squashed it to some meaningful commits. 
https://github.com/Azure/azure-iot-sdk-python/issues/179
The C SDK was modified to rectify the error. Previously when the message payload is empty it would still try send the message , but now the code has been modified to remove the empty message item from the list of messages waiting to be sent.

issue179 empty message problem on mqtt

---

device/tests/iothub_client_e2e.py

Jenkins is failing its nightly build for python end to end tests. This behavior is sporadic and is only happening for the blob upload test. The real cause has not been pin pointed yet and investigation will continue on VSTS.
The upload to blob test has been commented out.

Disable blob test for Jenkins stability

---

device/iothub_client_python/src/iothub_client_python.cpp
device/tests/iothub_client_ut.py

The method_id parameter wasn't properly marshalled between the boost wrapper and the python code.
Also, the boost wrapper was not unpacking the return value of the callback with the appropriate tag.

Fix for #230 - method callbacks

---

dockerfiles/Dockerfile_Rasp.build.armv7l_jessie
dockerfiles/Dockerfile_Rasp.build.armv7l_stretch

- [*] I have read the [contribution guidelines] (https://github.com/Azure/azure-iot-sdk-python/blob/master/.github/CONTRIBUTING.md).
- [*] This pull-request is submitted against the `master` branch. 
- [*] I have squashed my changes into one with a clear description of the change.
#274 - azure-iot-sdk-python dockerfiles for armv7l platforms are using deprecated base images provided by resin on Dockerhub. These should be updated to support newer images provided by balenalib.
Updated deprecated base images to point to new balenalib images

Update armv7l Dockerfiles for #274

---

azure-iot-device/azure/iot/device/common/async_adapter.py
azure-iot-device/azure/iot/device/common/evented_callback.py

* EventedCallback was logging successful callbacks in logger.info
* AsyncCallback was logging successful callbacks in logger.warning
* They both now use logger.debug

[LOGGING] Made AsyncCallback and EventedCallback use debug logs for success path

---

azure_provisioning_e2e/pytest.ini
azure_provisioning_e2e/tests/test_async_certificate_enrollments.py
azure_provisioning_e2e/tests/test_async_symmetric_enrollments.py
azure_provisioning_e2e/tests/test_sync_certificate_enrollments.py
azure_provisioning_e2e/tests/test_sync_symmetric_enrollments.py
requirements_test.txt

sometimes enrollments are being left out because we are cancelling builds and that is causing issues for the next build to run.
have added random uuids to the names of the registration names so that consecutive builds can run even with getting cancelled.
also added time out.

create random registration names

---

azure-iot-device/azure/iot/device/common/mqtt_transport.py
azure-iot-device/tests/common/test_mqtt_transport.py

This lets me speed up my dropped connection testing by at least an order or magnitude.  We should probably have an officially documented way to set this value, but I don't want that to get in the way.

Add DEFAULT_KEEPALIVE to speed up dropped connection test runs

---

azure-iot-device/azure/iot/device/common/chainable_exception.py
azure-iot-device/azure/iot/device/common/evented_callback.py
azure-iot-device/azure/iot/device/common/pipeline/operation_flow.py
azure-iot-device/azure/iot/device/common/pipeline/pipeline_ops_base.py
azure-iot-device/azure/iot/device/common/pipeline/pipeline_ops_mqtt.py
azure-iot-device/azure/iot/device/common/pipeline/pipeline_stages_base.py
azure-iot-device/azure/iot/device/common/pipeline/pipeline_stages_mqtt.py
azure-iot-device/azure/iot/device/iothub/pipeline/iothub_pipeline.py
azure-iot-device/azure/iot/device/iothub/pipeline/pipeline_ops_iothub.py
azure-iot-device/azure/iot/device/iothub/pipeline/pipeline_stages_iothub.py
azure-iot-device/azure/iot/device/iothub/pipeline/pipeline_stages_iothub_mqtt.py
azure-iot-device/azure/iot/device/provisioning/pipeline/pipeline_ops_provisioning.py
azure-iot-device/azure/iot/device/provisioning/pipeline/pipeline_stages_provisioning.py
azure-iot-device/azure/iot/device/provisioning/pipeline/pipeline_stages_provisioning_mqtt.py
azure-iot-device/azure/iot/device/provisioning/pipeline/provisioning_pipeline.py
azure-iot-device/tests/common/pipeline/helpers.py
azure-iot-device/tests/common/pipeline/pipeline_data_object_test.py
azure-iot-device/tests/common/pipeline/test_operation_flow.py
azure-iot-device/tests/common/pipeline/test_pipeline_ops_base.py
azure-iot-device/tests/common/pipeline/test_pipeline_ops_mqtt.py
azure-iot-device/tests/common/pipeline/test_pipeline_stages_base.py
azure-iot-device/tests/common/pipeline/test_pipeline_stages_mqtt.py
azure-iot-device/tests/iothub/pipeline/test_iothub_pipeline.py
azure-iot-device/tests/iothub/pipeline/test_pipeline_ops_iothub.py
azure-iot-device/tests/iothub/pipeline/test_pipeline_stages_iothub.py
azure-iot-device/tests/iothub/pipeline/test_pipeline_stages_iothub_mqtt.py
azure-iot-device/tests/provisioning/pipeline/test_pipeline_ops_provisioning.py
azure-iot-device/tests/provisioning/pipeline/test_pipeline_stages_provisioning.py
azure-iot-device/tests/provisioning/pipeline/test_pipeline_stages_provisioning_mqtt.py
azure-iot-device/tests/provisioning/pipeline/test_provisioning_pipeline.py

This is part of the retry changes factored out as it's own PR.  I did this for 2 reasons:
1. it made retry easier and cleaner
2. these things have been bothering me
This has 3 major changes:
1. I moved the error from an operation attribute into a callback parameter.  This is because the idea of an operation failing is becoming more transient with retry.  An error is not an integral part of an operation.  Rather, it's a temporary status that represents what happened to the operation most recently.  
2. The operation_flow.py methods are not part of the PipelineStage objects, which is sort-of what they were before.  I also renamed these to (I hope) make more sense.  
3. I added the idea that an op could be marked as "completed" and separated the concepts of `complete_op()` and …

refactor operation_flow as part of retry changes

---

azure-iot-device/azure/iot/device/iothub/aio/async_clients.py
azure-iot-device/azure/iot/device/iothub/sync_clients.py
azure-iot-device/azure/iot/device/provisioning/abstract_provisioning_device_client.py
azure-iot-device/azure/iot/device/provisioning/aio/async_provisioning_device_client.py
azure-iot-device/azure/iot/device/provisioning/provisioning_device_client.py
azure-iot-device/tests/provisioning/test_sync_provisioning_device_client.py

* Added missing elements of docstrings needed for correct API docs to IoTHub and DPS clients
* Correct exception docs in DPS will be added when exception surfacing is added.
* Removed `protocol_choice` parameter from DPS clients

docs: Further changes for correct API doc generation

---

azure-iot-device/azure/iot/device/common/pipeline/pipeline_stages_base.py
azure-iot-device/tests/common/pipeline/test_pipeline_stages_base.py

I hit this in E2E tests where old timers would hang around because they weren't cancelled.  Nothing bad happened, but we did leak objects when this happened and Horton flagged that as an error.

Cancel timeout stage timer when op is complete

---

azure-iot-device/azure/iot/device/iothub/abstract_clients.py
azure-iot-device/tests/iothub/aio/test_async_clients.py
azure-iot-device/tests/iothub/test_sync_clients.py

* This has only renamed ca_cert at API level - it still must be renamed throughout the stack

refactor(azure-iot-device): ca_cert parameter renamed to server_verification_cert

---

azure-iot-device/azure/iot/device/iothub/models/message.py
azure-iot-device/tests/iothub/aio/test_async_clients.py
azure-iot-device/tests/iothub/pipeline/test_pipeline_stages_iothub_mqtt.py
azure-iot-device/tests/iothub/test_sync_clients.py

Reverting the changes that was done here.
https://github.com/Azure/azure-iot-sdk-python/pull/315

fix(azure-iot-device): Revert changes for default content type and default content encoding

---

azure-iot-device/azure/iot/device/common/__init__.py
azure-iot-device/azure/iot/device/common/models/__init__.py
azure-iot-device/azure/iot/device/common/models/proxy_options.py
azure-iot-device/azure/iot/device/common/mqtt_transport.py
azure-iot-device/azure/iot/device/common/pipeline/config.py
azure-iot-device/azure/iot/device/common/pipeline/pipeline_stages_mqtt.py
azure-iot-device/azure/iot/device/common/transport_exceptions.py
azure-iot-device/azure/iot/device/iothub/abstract_clients.py
azure-iot-device/azure/iot/device/iothub/aio/async_clients.py
azure-iot-device/azure/iot/device/iothub/pipeline/exceptions.py
azure-iot-device/azure/iot/device/iothub/sync_clients.py
azure-iot-device/samples/async-hub-scenarios/send_message_via_proxy.py
azure-iot-device/samples/sync-samples/send_message_via_proxy.py
azure-iot-device/setup.py
azure-iot-device/tests/common/pipeline/test_pipeline_stages_mqtt.py
azure-iot-device/tests/common/test_mqtt_transport.py
azure-iot-device/tests/iothub/aio/test_async_clients.py
azure-iot-device/tests/iothub/test_sync_clients.py
requirements_test.txt

Proxy is only working for MQTT via web-sockets with HTTP proxy servers. Hence the samples have been defined accordingly to show case these specific scenarios. We are only going to support proxy via the above option.
However the implementation is general and we are not going to disallow usage of SOCK proxy servers with normal MQTT as well as MQTT web-sockets , but this is left to the user as an exercise.

feature(azure-iot-device):Support proxy via mqtt

---

azure-iot-device/azure/iot/device/iothub/abstract_clients.py
azure-iot-device/azure/iot/device/provisioning/abstract_provisioning_device_client.py

* Most methods were missing formal listing of ProxyOptions
* Adjusted the ProxyOptions class listing in the docstrings to reflect the correct namespacing for import

docs(azure-iot-device): Added ProxyOptions option to docstrings

---

azure-iot-device/setup.py
azure-iot-hub/setup.py

* For both `azure-iot-device` and `azure-iot-hub`:
* Prevented tests from accidentally being included in package distributions
* Removed the ability for samples to also be accidentally included

fix: Removed tests and samples from package distributions

---

azure-iot-device/azure/iot/device/iothub/abstract_clients.py
azure-iot-device/azure/iot/device/provisioning/abstract_provisioning_device_client.py

Type for `proxy_options` was formatted wrong.

fix(azure-iot-device): Correction to formatting of docstrings re: proxy_options

---

azure-iot-device/azure/iot/device/common/mqtt_transport.py
azure-iot-device/azure/iot/device/common/pipeline/pipeline_ops_base.py
azure-iot-device/azure/iot/device/common/pipeline/pipeline_stages_mqtt.py
azure-iot-device/tests/common/pipeline/test_pipeline_ops_base.py
azure-iot-device/tests/common/pipeline/test_pipeline_stages_mqtt.py
azure-iot-device/tests/common/test_mqtt_transport.py

There are conditions where connect and reconnect operations can timeout and we have no control.  These are very uncommon, but reproducable with the right stress scripts.  
To work around these conditions, I've added a watchdog timer to connect and reconnect operations.  If these operations don't complete within some interval (I picked 10 seconds), the watchdog cancels the operation and disconnects the transport.  This gives the transport a "clean slate" and the pipeline retry/reconnect logic is able to recover.
In some cases, the call into paho's mqtt_client.connect() never returns or takes a really long time to return.  (this has been seen in the field, but I haven't been able to reproduce this).  This is likely a bug in TLS  negotiation or the network stack.
We have no way to fix this. …

Add watchdog timer for MQTT connect and reconnect operations

---

azure-iot-device/azure/iot/device/__init__.py
azure-iot-device/azure/iot/device/aio/__init__.py

* Ensured that all exposed items in the regular and aio package are included in the __all__ definitions
* Docs should now generate correctly
* Added comments for clarity in the packaging structure

fix(azure-iot-device): Enabled generation of docs for missing items

---

azure-iot-device/samples/pnp/pnp_sample_device.py

I'd also suggest to remove the models from this repo, and point to the DTDL samples as the _source of truth_

chore(pnp) : Fix ModelID, deviceInfo convert to "com:example"

---

azure-iot-device/azure/iot/device/iothub/abstract_clients.py
azure-iot-device/azure/iot/device/provisioning/abstract_provisioning_device_client.py
azure-iot-device/tests/iothub/shared_client_tests.py
azure-iot-device/tests/provisioning/shared_client_tests.py

* Added support for custom SasToken TTL via the 'sastoken_ttl' kwarg on SAS-based factory methods of the IoTHub clients
* Added support for custom SasToken TTL via the 'sastoken_ttl' kwarg on SAS-based facotry methods of the Provisioning clients

feature (azure-iot-device): Add 'sastoken_ttl' kwarg option to factory methods

---

env_setup.py

`os.system(command)` is one way to use running terminal commands.
Since we are using `check_call` here to achieve the same `shell=True` is one way to tell that call that we are trying to run a terminal command.

fix : pre-commit error

---

azure-iot-device/azure/iot/device/iothub/pipeline/mqtt_topic_iothub.py
azure-iot-device/azure/iot/device/iothub/pipeline/pipeline_stages_iothub_mqtt.py
azure-iot-device/tests/iothub/pipeline/test_mqtt_topic_iothub.py

- Removed URL encoding from module id and device id in topic strings
- Left all other URL encoding in topic strings in place for now, since this issue only really affected device and module ids. When Hub makes a new API, we will be able to return to URL encoding all values for consistency

fix(azure-iot-device): Fixed errors when using device/module ids with special characters

---

azure-iot-device/azure/iot/device/iothub/abstract_clients.py

- Fixed indentation so docs generate correctly

fix(azure-iot-device): Fixed indentation for sastoken_ttl kwarg

---

azure-iot-device/azure/iot/device/aio/patch_documentation.py
azure-iot-device/azure/iot/device/patch.py
azure-iot-device/azure/iot/device/patch_documentation.py

* Adjusted patching scripts so client properties (incl. handlers) are dynamically moved to leaf classes from parents, so that online API documentation can correctly ingest
* Adjusted patching scripts for correct ingestion of the .shutdown() method as well
* Fixes GitHub issue #725

fix (azure-iot-device): Patching script adjustments for properties

---

azure-iot-device/.bumpverion.cfg
azure-iot-device/azure/iot/device/constant.py

* Bump versions for azure-iot-device 2.5.1

release(azure-iot-device): Release 2021-02-16 Version Bump (2.5.1)

---

azure-iot-device/setup.py

requests can support urllib3 1.26.x.  This change avoids a warning since we say that we don't support 1.26, when we don't really care.

change urllib3 versions to avoid warnings

---

azure-iot-device/azure/iot/device/iothub/models/message.py
azure-iot-device/azure/iot/device/iothub/pipeline/mqtt_topic_iothub.py
azure-iot-device/tests/iothub/models/test_message.py
azure-iot-device/tests/iothub/pipeline/test_mqtt_topic_iothub.py

- The `iothub-ack` system property is now available to users via the `ack` attribute of the `Message` object on C2D messages

feature(azure-iot-device): Enable support for 'iothub-ack' system property on C2D messages

---

azure-iot-device/.bumpverion.cfg
azure-iot-device/azure/iot/device/constant.py

release(azure-iot-device): Bump package versions for release on 2021-06-04

---

azure-iot-device/azure/iot/device/iothub/__init__.py
azure-iot-device/azure/iot/device/iothub/abstract_clients.py
azure-iot-device/azure/iot/device/iothub/aio/async_clients.py
azure-iot-device/azure/iot/device/iothub/models/commands.py
azure-iot-device/azure/iot/device/iothub/models/pnp_translation.py
azure-iot-device/azure/iot/device/iothub/sync_clients.py
azure-iot-device/tests/iothub/aio/test_async_clients.py
azure-iot-device/tests/iothub/client_fixtures.py
azure-iot-device/tests/iothub/conftest.py
azure-iot-device/tests/iothub/shared_client_tests.py
azure-iot-device/tests/iothub/test_sync_clients.py

* Added a new internal "client_mode" attribute to track whether PNP is in use or not
* Added logic that will lock out certain APIs and properties depending on the mode
* Added (partial) implementation of PNP handlers + test stubs

feature(azure-iot-device): Added internal PNP mode

---

azure-iot-device/azure/iot/device/common/pipeline/config.py
azure-iot-device/azure/iot/device/common/pipeline/pipeline_stages_base.py
azure-iot-device/azure/iot/device/iothub/abstract_clients.py
azure-iot-device/tests/common/pipeline/config_test.py
azure-iot-device/tests/common/pipeline/test_pipeline_stages_base.py

Fixed an issue where sufficiently long SAS token expiry or retry interval could cause a OverflowError due to exceeding the max value supported by a waiting thread

fix(azure-iot-device): OverflowError for sufficiently long SAS expiry or retry interval

---

azure-iot-device/azure/iot/device/common/pipeline/pipeline_stages_base.py

Fixed an issue where after a failed reauthorization, the re-attempt of the reauthorization happened on the wrong thread

fix(azure-iot-device): Reauthorization on wrong thread

---

azure-iot-device/azure/iot/device/common/auth/connection_string.py
azure-iot-device/azure/iot/device/iothub/abstract_clients.py
azure-iot-device/azure/iot/device/provisioning/abstract_provisioning_device_client.py
azure-iot-device/tests/common/auth/test_connection_string.py
azure-iot-device/tests/iothub/shared_client_tests.py
azure-iot-device/tests/provisioning/shared_client_tests.py

* Added `gateway_hostname` user option to `.create_from_sastoken()`, `.create_from_x509_certificate()` and `.create_from_symmetric_key()` on the Device/Module IoTHub Clients
* Added `gateway_hostname` user option to all factory methods on the Provisioning Clients

feature(azure-iot-device): Added support for user-provided gateway_hostname

---

scripts/build-release.ps1

For some reason `python.exe` stopped working but `python` still does
¯\_(ツ)_/¯

fix: release script

---

azure-iot-device/azure/iot/device/common/http_transport.py
azure-iot-device/tests/common/test_http_transport.py

* Added the recommended 'timeout' argument to the `HTTPTransport`'s invocation of the `requests` library
* Intentionally did not provide customization in lieu of overarching timeout strategy.

fix(azure-iot-device): Added timeout to HTTP requests

---

azure-iot-device/azure/iot/device/common/mqtt_transport.py
azure-iot-device/azure/iot/device/common/pipeline/pipeline_stages_mqtt.py
azure-iot-device/setup.py
azure-iot-device/tests/common/pipeline/test_pipeline_stages_mqtt.py
azure-iot-device/tests/common/test_mqtt_transport.py

There are three side-effects of this, two actual and one theoretical:
1. If Paho fails to receive a PINGRESP, it will return this RC, and the code in RetryConnectionStage will not try to reconnect.  This _should_ cause a failure to be returned to the client, but it will be a generic `ProtocolClientError` instead of a `ConnectionDroppedError`.
2. The log line printed `Unknown CONNACK rc=16` which is incorrect. This was not a `CONNACK` rc.
Also including a change that was found at the same time.  If transport.disconenct raises inside the connection watchdog, the pending connection op would never complete.

fix (azure-iot-device) Add MQTT_ERR_KEEPALIVE mapping to fix connection issues caused by new Paho error code

---

azure-iot-device/azure/iot/device/common/pipeline/pipeline_stages_base.py
azure-iot-device/azure/iot/device/iothub/pipeline/mqtt_pipeline.py
azure-iot-device/azure/iot/device/provisioning/pipeline/mqtt_pipeline.py
azure-iot-device/tests/common/pipeline/test_pipeline_stages_base.py
azure-iot-device/tests/iothub/pipeline/test_mqtt_pipeline.py
azure-iot-device/tests/provisioning/pipeline/test_mqtt_pipeline.py

ReconnectStage renamed to ConnectionStateStage. This is because I have changed the stage such that the connection state machine logic is now in use, even when not using connection_retry. Naturally, connection retry / reconnect functionality is only used if the user option has been enabled.
Note that this change has no meaningful change in functionality - the state machine running when not using connection_retry doesn't mean much if it's not being used to reconnect. Only real difference is that now when not using connection_retry operations will queue here in addition to the ConnectionLockStage if a connection is in progress so that we can ensure the state is what we think it is, but that really doesn't change anything.
This is necessary as an intermediate step to unifying the connection …

refactor(azure-iot-device): ReconnectStage -> ConnectionStateStage

---

azure-iot-device/azure/iot/device/common/pipeline/pipeline_stages_base.py
azure-iot-device/azure/iot/device/iothub/pipeline/pipeline_stages_iothub.py

* Stages (except the MQTTTransportStage) now always invoke `.send_event_up`() at the _end_ of the `.handle_pipeline_event()` call
* Now that connection state has been improved by previous PRs, we no longer have to work around timing issues by invoking `.send_event_up()` early
* By doing things in the correct order, we now will no longer be accidentally republishing the twin GET that triggers upon connection
* Fixes #994

fix (azure-iot-device): Prevent duplicate twin GET upon Connect

---

azure-iot-device/azure/iot/device/common/pipeline/pipeline_stages_base.py
azure-iot-device/azure/iot/device/iothub/pipeline/mqtt_pipeline.py
azure-iot-device/azure/iot/device/provisioning/pipeline/mqtt_pipeline.py
azure-iot-device/tests/common/pipeline/test_pipeline_stages_base.py
azure-iot-device/tests/iothub/pipeline/test_mqtt_pipeline.py
azure-iot-device/tests/provisioning/pipeline/test_mqtt_pipeline.py

* All remaining `ConnectionLockStage` functionality that was not already implemented by the `ConnectionStateStage` has now been moved there
* It's about time

refactor (azure-iot-device): Remove ConnectionLockStage

---

azure-iot-device/azure/iot/device/common/http_transport.py
azure-iot-device/azure/iot/device/common/mqtt_transport.py
tests/unit/common/test_http_transport.py
tests/unit/common/test_mqtt_transport.py

In Python 3.6 the constant `PROTOCOL_TLSv1_2` has been deprecated

fix: Updated TLS constant

---

.gitignore
migration_guide.md
requirements_test.txt
v3_async_wip/tests/simple_e2e.py
v3_async_wip/tests/test_config.py
v3_async_wip/tests/test_iothub_mqtt_client.py
v3_async_wip/tests/test_models.py
v3_async_wip/tests/test_mqtt_topic_iothub.py
v3_async_wip/tests/test_user_agent.py
v3_async_wip/v3_async_wip/config.py
v3_async_wip/v3_async_wip/iothub_mqtt_client.py
v3_async_wip/v3_async_wip/models.py
v3_async_wip/v3_async_wip/mqtt_client.py
v3_async_wip/v3_async_wip/mqtt_topic_iothub.py
v3_async_wip/v3_async_wip/user_agent.py

* Ported user_agent.py and added typings for V3 
* Ported, added typings and simplified mqtt_topic_iothub.py for V3
* Enhanced Message class to make properties and topics easier to use internally.
* Enhanced Message-related logic to be more rigid about expected typings
* Added full support for JSON payloads when sending/receiving messages
* APIs related to Device/Module-specific features now throw exceptions if not using the correct configuration

[V3] Enhanced reused modules for V3

---

v3_async_wip/tests/test_iothub_client.py
v3_async_wip/tests/test_iothub_http_client.py
v3_async_wip/tests/test_iothub_mqtt_client.py
v3_async_wip/v3_async_wip/iothub_client.py
v3_async_wip/v3_async_wip/iothub_http_client.py
v3_async_wip/v3_async_wip/iothub_mqtt_client.py

* Simplified `.shutdown()` implementations with use of `asyncio.shield()`
* Marked tests where some more complex mocking is required to truly demonstrate the accuracy of shutdown (low priority for now)
* Added try/finally blocks to tests that could hang upon assertion failure due to the mocking of methods that are required for teardown

[V3] Simplified shutdown

---

azure-iot-device/azure/iot/device/iothub/pipeline/pipeline_stages_iothub_http.py
azure-iot-device/azure/iot/device/iothub/pipeline/pipeline_stages_iothub_mqtt.py
tests/unit/iothub/pipeline/test_pipeline_stages_iothub_mqtt.py

-  (n/a) If this is a modification that impacts the behavior of a public API
#1081 
Method request with no payload were raising a json decode issue like mentioned in #1081.
Added a oneliner to manage empty payloads.
MQTT tests updated too.
HTTP tests: I did not find the way to test this specific change.

Fix: empty payload

---

v3_async_wip/tests/test_mqtt_topic_provisioning.py
v3_async_wip/tests/test_request_response.py
v3_async_wip/v3_async_wip/mqtt_topic_iothub.py
v3_async_wip/v3_async_wip/mqtt_topic_provisioning.py
v3_async_wip/v3_async_wip/request_response.py

* Ported `mqtt_topic_provisioning` and associated tests
* Added support for custom `request_id` in `request_response` module to support DPS query functionality

[V3] Infrastructure to support ProvisioningMQTTClient

---

v3_async_wip/tests/test_iothub_mqtt_client.py
v3_async_wip/tests/test_iothub_session.py
v3_async_wip/tests/test_mqtt_client.py
v3_async_wip/v3_async_wip/iothub_mqtt_client.py
v3_async_wip/v3_async_wip/iothub_session.py
v3_async_wip/v3_async_wip/mqtt_client.py

* Removed SAS renewal logic in the IoTHubMQTTClient.
* Added support for reporting connection drop errors in MQTTClient and IoTHubMQTTClient
* Modified IoTHubSession receiver generators to raise error in the case of connection drop / disconnection
* Modified outgoing data IoTHubSession APIs to raise error in the case of connection drop / disconnection
* Added basic `sastoken_ttl` argument support
NOTE: Auth API adjustments to reflect the lack of SAS renewal will be part of a separate PR

[V3] Allow connection loss to propagate through APIs and generators

---

setup.py

`requests` 2.32.0 broke `requests-unixsocket`. This breaks IoT Edge functionality.
Until we can find a long-term solution, we are restricting the version of `requests`.

Restricted requests version for unixsocket compatibility

---

.devcontainer/Dockerfile
.devcontainer/devcontainer.json
README.md
samples/README.md
scripts/configure-virtual-environments.sh
setup.py
tests/unit/iothub/aio/test_async_clients.py
tests/unit/iothub/test_sync_clients.py
tests/unit/provisioning/models/test_registration_result.py
vsts/build.yaml
vsts/dps-e2e.yaml
vsts/python-canary.yaml
vsts/python-e2e.yaml
vsts/python-nightly.yaml

* `requests` had critical security fixes that required updating minimum version
* This fix broke the `requests-unixsocket` dependency which used monkey-patching
* `requests-unixsocket` is abandoned, so switched to use the fork `requests-unixsocket2`
* Also updated `urllib3` dependency to be more flexible.
* Added support for Python 3.11 and 3.12

Updated dependencies to fix breaking changes in requests

---

samples/sync-samples/provision_symmetric_key.py

Current implementation of the sync version of `provision_symmetric_key.py` calls disconnect API repeatedly, it seems weird.
I think it would be correct just as the async version [samples/async-hub-scenarios/provision_symmetric_key.py](https://github.com/Azure/azure-iot-sdk-python/blob/main/samples/async-hub-scenarios/provision_symmetric_key.py#L56) does.

bugfix: sample: disconnect when all the messages are sent

---

.pre-commit-config.yaml

```
_load_entrypoint_plugins
eps = importlib_metadata.entry_points().get(self.namespace, ())
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'EntryPoints' object has no attribute 'get'
```
Bump flake8 pre-commit hook version from 3.9.1 to 7.0.0.

Fix importlib_metadata.entry_points attribute error by updating flake8
