device/samples/iothub_client_sample.py, device/samples/iothub_client_sample_class.py, device/samples/iothub_client_sample_x509.py
Added temperature and humidity to packet, in order to make sample compatible with our advanced tutorials at docs.microsoft.com
=> Added temperature and humidity to packet

device/iothub_client_python/src/iothub_client_python.cpp
=> Fix a build error when building without AMQP

readme.md
- I submitted this PR against the correct branch:
=> sdk readme update

doc/python-devbox-setup.md, readme.md
- [ x] I have read the [contribution guidelines] (https://github.com/Azure/azure-iot-sdk-python/blob/master/.github/CONTRIBUTING.md).
- [ x] I added or modified the existing tests to cover the change (we do not allow our test coverage to go down).
- [x ] This pull-request is submitted against the `master` branch. 
Readme didn't include clone --recursive on build page.
Added clone
=> Update readme to include clone on build page

doc/python-devbox-setup.md
On some machines pip cannot be found.
=> Adding note about installing PIP

doc/python-devbox-setup.md
Modify readme to add a note regarding x64 python
=> Add note regarding version of python

device/iothub_client_python/src/iothub_client_python.cpp, provisioning_device_client/src/provisioning_device_client_python.cpp, service/src/iothub_service_client_python.cpp
Bump package versions after fixing the Raspberry pi pip issues, the MacOS build and snapping to the latest C SDK version
=> Bump to version 1.4.1 on 2018-07-16

device/iothub_client_python/src/iothub_client_python.cpp, provisioning_device_client/src/provisioning_device_client_python.cpp, service/src/iothub_service_client_python.cpp
Update the C submodule reference and bump version to 1.4.2
=> Bump version to 1.4.2

build_all/mac/release.sh, build_all/mac/setup.sh
- I submitted this PR against the correct branch:
=> Create Python 3 release packages

device/samples/iothub_client_sample.py
The code becomes more readable and thereby easier to understand.
=> Extract wind_speed into a variable

device/samples/edge_downstream_client.py
- [x ] I have read the [contribution guidelines] (https://github.com/Azure/azure-iot-sdk-python/blob/master/.github/CONTRIBUTING.md).
- [ x] I added or modified the existing tests to cover the change (we do not allow our test coverage to go down).
Providing a sample to make it easier for users to connect downstream devices to an Azure IoT Edge device,
Added a sample that highlights how a developer should put together a connection string for the Edge and install the relevant CA certificate required to authenticate the Azure IoT Edge server certificate. The sample was based off iothub_client_simple_sample.py with the required pieces to connect to an Edge.
=> Sample code for a downstream device that connects to an IoT Edge device

readme.md
Add azure pipelines badge based on the python-canary build.
=> Add build badge (python-canary)

device/iothub_client_python/src/iothub_client_python.cpp, provisioning_device_client/src/provisioning_device_client_python.cpp, service/src/iothub_service_client_python.cpp
=> Update to v1.4.4 for LTS release 10_2018

build_all/linux/release.sh, dockerfiles/Dockerfile_Linux.build.arm64v8_xenial
Created docker file for ARM64V8 build of SDK for Linux
Tested on Ubuntu-Tegra 16.04 TX2 Device.
- [x ] I have read the [contribution guidelines](https://github.com/Azure/azure-iot-sdk-python/blob/master/.github/CONTRIBUTING.md).
- [x ] This pull-request is submitted against the `master` branch. 
- [x ] I have merged the latest `master` branch prior to submission and re-merged as needed after I took any feedback.
- [x ] I have squashed my changes into one with a clear description of the change.
[Request for ARM64v8/aarch64 build of the SDK #232](https://github.com/Azure/azure-iot-sdk-python/issues/232)
Missing azure-iot-sdk-python for Linux ARM64v8 Devices.
Created a …
=> Regarding Issue #232

device/samples/module_method.py
Adding a sample that shows how to receive and respond to methods from a module client.
=> Add module method sample

device/iothub_client_python/src/iothub_client_python.cpp, device/iothub_client_python/test/iothub_client_mock.cpp, provisioning_device_client/src/provisioning_device_client_python.cpp, provisioning_service_client/setup.py, service/src/iothub_service_client_python.cpp
New features for the C submodule include support for trusted certs on windows which will enable the VS Code extension to support module debugging with the python SDK
The provisioning service SDK is also getting an update with all the new anniversary update features (custom allocation policies, symmetric key attestation etc)
=> Update C submodule and package version for 2018-12-13

device/samples/iothub_client_file_upload.py, service/samples/iothub_registrymanager_sample.py
#241 
user_context usage wasn't clear in the samples
Added comment.
=> fix(#241): Add user_context comment in file upload sample

doc/python-devbox-setup.md
- [n/a] I added or modified the existing tests to cover the change (we do not allow our test coverage to go down).
- [n/a] I edited the corresponding document in the `devdoc` folder and added or modified requirements.
Instructions in python-devbox-setup.md had some typos
Fixed the typos
=> Instruction typo fixes

azure-iot-device/README.md, azure-iot-device/samples/README.md, azure-iot-device/samples/advanced-hub-scenarios/README.md, azure-iot-device/samples/legacy-samples/README.md
* Fixed broken links in sample README
* Added some details re: using samples
=> [DOCUMENTATION] Fixed broken links in sample README

azure-iot-hub/azure/iot/hub/iothub_registry_manager.py
=> Merge master

azure-iot-device/README.md, azure-iot-device/setup.py, azure-iot-hub/azure/iot/hub/constant.py, azure-iot-hub/setup.py, azure-iot-nspkg/setup.py
* Added specific repo links to setup.py files rather root monorepo
* Removed an broken link in monorepo root README.md
* Corrected the version number of azure-iot-hub
=> [INFRASTRUCTURE] Correct links and versioning

azure-iot-hub/azure/iot/hub/iothub_registry_manager.py
* Made clearer the inputs for the "status" parameter
* Attempted to add a linkable class definition for the HttpOperationError
* Considerations re: object docs (e.g. Device, Module, ServiceStatistics, etc.) will be added at a later date
=> doc: Hub docstring changes for docgen

README.md, azure-iot-hub/README.md, azure-iot-hub/azure/iot/hub/constant.py
* Removed unincluded features from azure-iot-hub README
* Simplified azure-iot-hub README
* Fixed broken links in monorepo README
* Bumped version
=> release(azure-iot-hub): 2.0.0.preview.2

azure-iot-device/.bumpverion.cfg, azure-iot-device/azure/iot/device/constant.py
=> release(azure-iot-device): 2.0.0-preview.12

azure-iot-device/azure/iot/device/common/chainable_exception.py, azure-iot-device/azure/iot/device/common/mqtt_transport.py, azure-iot-device/azure/iot/device/common/pipeline/pipeline_exceptions.py, azure-iot-device/azure/iot/device/common/pipeline/pipeline_ops_mqtt.py, azure-iot-device/azure/iot/device/common/pipeline/pipeline_stages_base.py, azure-iot-device/azure/iot/device/common/transport_exceptions.py, azure-iot-device/azure/iot/device/iothub/pipeline/iothub_pipeline.py, azure-iot-device/tests/common/pipeline/test_pipeline_ops_mqtt.py, azure-iot-device/tests/common/pipeline/test_pipeline_stages_base.py, azure-iot-device/tests/iothub/pipeline/test_iothub_pipeline.py, azure-iot-device/tests/provisioning/internal/test_polling_machine.py
This is the base case for retry which covers retry on sub and unsub.  This should be easily expanded for other scenarios.
I know that the tests will probably change once Carter is done with his changes, but I think the substance will stay the same.
=> Simple Retry Impl

azure-iot-device/azure/iot/device/provisioning/pipeline/pipeline_stages_provisioning.py, azure-iot-device/azure/iot/device/provisioning/pipeline/pipeline_stages_provisioning_mqtt.py, azure-iot-device/azure/iot/device/provisioning/pipeline/provisioning_pipeline.py, azure-iot-device/tests/provisioning/pipeline/test_pipeline_stages_provisioning.py, azure-iot-device/tests/provisioning/pipeline/test_provisioning_pipeline.py
Added tests for pipeline.
Some code looks to have undergone space changes.
=> tests(azure-iot-device): pipeline tests

azure-iot-device/tests/common/pipeline/test_pipeline_stages_base.py, azure-iot-device/tests/common/pipeline/test_pipeline_stages_mqtt.py, azure-iot-device/tests/common/test_mqtt_transport.py, azure-iot-device/tests/iothub/aio/test_async_clients.py, azure-iot-device/tests/iothub/pipeline/test_iothub_pipeline.py, azure-iot-device/tests/iothub/pipeline/test_pipeline_stages_iothub.py, azure-iot-device/tests/iothub/test_sync_clients.py
this resolves a small naming issue in the tests
=> rename(azure-iot-device): EVENT to OCCURANCE

azure-iot-device/azure/iot/device/common/mqtt_transport.py, azure-iot-device/azure/iot/device/common/transport_exceptions.py, azure-iot-device/azure/iot/device/iothub/aio/async_clients.py, azure-iot-device/azure/iot/device/iothub/pipeline/exceptions.py, azure-iot-device/azure/iot/device/iothub/sync_clients.py, azure-iot-device/tests/common/test_mqtt_transport.py, azure-iot-device/tests/iothub/aio/test_async_clients.py, azure-iot-device/tests/iothub/test_sync_clients.py, azure-iot-hub/samples/iothub_registry_manager_statistics_sample.py
Have replicated the scenario in all python versions
=> fix(azure-iot-device): Stop Retrying on SSL Verify Cert Error 

azure-iot-device/tests/provisioning/pipeline/test_pipeline_stages_provisioning.py, azure-iot-device/tests/provisioning/pipeline/test_provisioning_pipeline.py
Let this PR go first to fix other stuff
=> fix(azure-iot-device): fixed parametrization

azure-iot-device/azure/iot/device/common/http_transport.py, azure-iot-device/azure/iot/device/common/pipeline/pipeline_stages_http.py, azure-iot-device/tests/common/pipeline/test_pipeline_stages_http.py, azure-iot-device/tests/common/test_http_transport.py
* Cipher now works for HTTP operations
=> feature(azure-iot-device): Added cipher functionality to HTTP pipeline

scripts/cert_gen.sh
A hard coded password was used to create our test certs.
User can pass in the password now.
=> chore(azure-iot-device) : User choice password

azure-iot-device/.bumpverion.cfg, azure-iot-device/azure/iot/device/constant.py
=> release(azure-iot-device)Bump package versions for release on 2020-04-01

azure-iot-device/setup.py, azure-iot-hub/setup.py
* Fixed version extraction to remove spurious quotation marks (") being included, which got turned into dashes (-) when building packages.
=> fix: Corrected version extraction in setup.py

.github/CONTRIBUTING.md, .github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md, README.md
Thank you for helping us improve the Azure IoT Python SDK!
Here's a little checklist of things that will …
=> chore: Update ReadMe.md files from formatting fixes

azure-iot-device/samples/async-hub-scenarios/upload_to_blob.py
This is to address feedback from @BertKleewein on the upload sample. Should provide better error handling for a host of error responses that could happen with the Storage SDK calls, and slightly cleaner code.
=> chore(azure-iot-device): clean up upload to blob sample code

azure-iot-device/azure/iot/device/iothub/pipeline/mqtt_pipeline.py, azure-iot-device/tests/iothub/pipeline/test_mqtt_pipeline.py
=> fix (azure-iot-device): Issue 517 - Don't set feature_enabled flag until subscribe succeeds

azure-iot-device/README.md
=> fix: link to samples

azure-iot-hub/azure/iot/hub/__init__.py, azure-iot-hub/azure/iot/hub/iothub_amqp_client.py, azure-iot-hub/azure/iot/hub/iothub_configuration_manager.py, azure-iot-hub/azure/iot/hub/iothub_http_runtime_manager.py, azure-iot-hub/azure/iot/hub/iothub_job_manager.py, azure-iot-hub/samples/iothub_job_manager_sample.py, azure-iot-hub/tests/test_iothub_amqp_client.py, azure-iot-hub/tests/test_iothub_http_runtime_manager.py, azure-iot-hub/tests/test_job_manager.py
=> Add job client

azure-iot-hub/samples/iothub_digital_twin_manager_sample.py
=> Add Json patch sample

.github/workflows/syncToDevOps.yml
=> chore: sync issues to azure devOps

.github/ISSUE_TEMPLATE/bug-report.md, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/technical-question.md, .github/PULL_REQUEST_TEMPLATE.md, README.md
=> chore: update readme

azure-iot-device/azure/iot/device/constant.py
=> chore: rename digital-twin-model-id to modelId in mqtt (Merge pending Deployment)

azure-iot-device/.bumpverion.cfg, azure-iot-device/azure/iot/device/constant.py
Incorporates model id changes for PNP in the package
=> Bump package versions for release on 2020-07-02

azure-iot-device/samples/pnp/pnp_helper_summer_refresh.py, azure-iot-device/samples/pnp/pnp_temp_controller_with_thermostats.py
So that there is very little difference between the non-PNP and pnp device.
=> fix(pnp) : Added pure helper

azure-iot-device/samples/pnp/pnp_thermostat.py
following the thermostat DTMI https://github.com/Azure/opendigitaltwins-dtdl/blob/master/DTDL/v2/samples/Thermostat.json
=> chore(pnp): no component sample

azure-iot-hub/azure/iot/hub/iothub_registry_manager.py, azure-iot-hub/samples/iothub_registry_mgr_update_x509.py
=> chore: fixing service client update device functions (#613)

azure-iot-hub/azure/iot/hub/iothub_digitaltwin_manager.py, azure-iot-hub/samples/pnp_invoke_command_sample.py, azure-iot-hub/samples/pnp_invoke_component_command_sample.py, azure-iot-hub/tests/test_digitaltwin_manager.py
=> feat(azure-iot-hub): add options to invoke(s)

README.md
=> chore: Add API reference links to readme

azure-iot-device/samples/pnp/pnp_temp_controller_with_thermostats.py
https://msazure.visualstudio.com/One/_workitems/edit/7710384
=> fix(pnp) : Update response to not include name

azure-iot-device/samples/pnp/pnp_temp_controller_with_thermostats.py
https://msazure.visualstudio.com/One/_workitems/edit/7710384
=> fix(pnp): exclude name from response object

README.md
=> chore: add link to survey on the readme

azure-iot-device/azure/iot/device/common/pipeline/pipeline_stages_base.py
https://github.com/Azure/azure-iot-sdk-python/issues/647
Changing the message to track that all operations of republish should only be a get twin.
=> fix(azure-iot-device) : Logger level and republish

README.md
=> chore: remove survey link from readme

azure-iot-hub/azure/iot/hub/__init__.py, azure-iot-hub/azure/iot/hub/digital_twin_client.py, azure-iot-hub/samples/get_digital_twin_sample.py, azure-iot-hub/samples/invoke_command_sample.py, azure-iot-hub/samples/invoke_component_command_sample.py, azure-iot-hub/samples/pnp_iothub_registry_manager_sample.py, azure-iot-hub/samples/update_digital_twin_sample.py, azure-iot-hub/tests/test_digital_twin_client.py
=> Rename to DigitalTwinClient

azure-iot-device/.bumpverion.cfg, azure-iot-device/azure/iot/device/constant.py, azure-iot-hub/.bumpverion.cfg, azure-iot-hub/azure/iot/hub/constant.py
PnP GA for both Device and Hub
=> chore : Bump package versions for release on 2020-09-29 

azure-iot-device/azure/iot/device/iothub/abstract_clients.py
=> Edited DocString in abstract_clients.py from keepalive to keep_alive

azure-iot-device/.bumpverion.cfg, azure-iot-device/azure/iot/device/constant.py
=> release(azure-iot-device): Release 2020-11-05

azure-iot-device/samples/pnp/README.md, azure-iot-device/samples/pnp/temp_controller_with_thermostats.py
Make this sample compatible with Central (uses different models for each component)
=> Em tempcontroller v2

azure-iot-device/samples/pnp/README.md
=> fix: broken pnp links

azure-iot-device/azure/iot/device/common/mqtt_transport.py, azure-iot-device/azure/iot/device/common/pipeline/config.py, azure-iot-device/azure/iot/device/common/pipeline/pipeline_stages_base.py, azure-iot-device/azure/iot/device/common/transport_exceptions.py, azure-iot-device/azure/iot/device/exceptions.py, azure-iot-device/azure/iot/device/iothub/abstract_clients.py, azure-iot-device/azure/iot/device/iothub/aio/async_clients.py, azure-iot-device/azure/iot/device/iothub/pipeline/exceptions.py, azure-iot-device/azure/iot/device/iothub/pipeline/mqtt_pipeline.py, azure-iot-device/azure/iot/device/iothub/sync_clients.py, azure-iot-device/tests/common/pipeline/config_test.py, azure-iot-device/tests/common/pipeline/test_pipeline_stages_base.py, azure-iot-device/tests/common/test_mqtt_transport.py, azure-iot-device/tests/iothub/aio/test_async_clients.py, azure-iot-device/tests/iothub/shared_client_tests.py, azure-iot-device/tests/iothub/test_sync_clients.py
* Added optional ability to disable autoconnect via kwarg
=> feature(azure-iot-device): Disable autoconnect

azure-iot-hub/azure/iot/hub/iothub_registry_manager.py, azure-iot-hub/tests/test_iothub_registry_manager.py
=> Registry etag fixes

azure-iot-hub/samples/iothub_job_manager_sample.py
Only changing a sample here. No need to change any implementation for user assigned identities. We got this for free when regenerating the code for parentScopes.
=> Update job manager sample for user assigned identities

azure-iot-device/samples/pnp/README.md
These updates are part of the changes needed to onboard these samples to the Azure Samples browser experience.
=> Update readme for PnP samples

.pre-commit-config.yaml, azure-iot-hub/azure/iot/hub/auth.py, azure-iot-hub/azure/iot/hub/digital_twin_client.py, azure-iot-hub/azure/iot/hub/iothub_configuration_manager.py, azure-iot-hub/azure/iot/hub/iothub_http_runtime_manager.py, azure-iot-hub/azure/iot/hub/iothub_job_manager.py, azure-iot-hub/azure/iot/hub/iothub_registry_manager.py, azure-iot-hub/samples/iothub_registry_manager_token_credential_sample.py, azure-iot-hub/setup.py, azure-iot-hub/tests/test_digital_twin_client.py, azure-iot-hub/tests/test_iothub_http_runtime_manager.py, azure-iot-hub/tests/test_job_manager.py
=> AAD token credential authentication (http)

azure-iot-device/.bumpverion.cfg, azure-iot-device/azure/iot/device/common/mqtt_transport.py, azure-iot-device/azure/iot/device/common/pipeline/pipeline_stages_base.py, azure-iot-device/azure/iot/device/common/pipeline/pipeline_stages_mqtt.py, azure-iot-device/azure/iot/device/constant.py, azure-iot-device/azure/iot/device/iothub/abstract_clients.py, azure-iot-device/azure/iot/device/iothub/aio/async_clients.py, azure-iot-device/azure/iot/device/iothub/pipeline/mqtt_pipeline.py, azure-iot-device/azure/iot/device/iothub/sync_clients.py, azure-iot-device/tests/common/pipeline/test_pipeline_stages_base.py, azure-iot-device/tests/common/pipeline/test_pipeline_stages_mqtt.py, azure-iot-device/tests/common/test_mqtt_transport.py, azure-iot-device/tests/iothub/aio/test_async_clients.py, azure-iot-device/tests/iothub/test_sync_clients.py
Merged with the latest commits from master branch in order to bring some reorganization in.
=> Merge Master Changes to PNP

azure-iot-device/tests/common/pipeline/test_pipeline_stages_base.py, azure-iot-device/tests/common/pipeline/test_pipeline_stages_mqtt.py, azure-iot-device/tests/common/test_mqtt_transport.py, azure-iot-device/tests/iothub/aio/test_async_clients.py, azure-iot-device/tests/iothub/pipeline/test_mqtt_pipeline.py, azure-iot-device/tests/iothub/pipeline/test_pipeline_stages_iothub.py, azure-iot-device/tests/iothub/shared_client_tests.py, azure-iot-device/tests/iothub/test_sync_clients.py
* Finally fixed this in test code
=> chore(azure-iot-device): Fixed "occurrence" typos

README.md
I'm adding these notices to all or our repos so that users have plenty of time to add the new public certificate to their device's certificate store before this change happens
=> Add notice about upcoming service TLS changes to the readme

azure-iot-device/azure/iot/device/iothub/abstract_clients.py, azure-iot-device/azure/iot/device/iothub/aio/async_clients.py, azure-iot-device/azure/iot/device/iothub/sync_clients.py, azure-iot-device/tests/iothub/aio/test_async_clients.py, azure-iot-device/tests/iothub/client_fixtures.py, azure-iot-device/tests/iothub/conftest.py, azure-iot-device/tests/iothub/shared_client_tests.py, azure-iot-device/tests/iothub/test_sync_clients.py
* Removed global PNP/Basic client modes
* Replaced them with handler-specific handler modes
* Made additional testing improvements
=> fix(azure-iot-device): Removed global PNP/Basic modes for client

azure-iot-hub/.bumpverion.cfg, azure-iot-hub/azure/iot/hub/constant.py
* Add support for C2D messages with AAD authentication
=> release(azure-iot-hub): Bump package versions for release on 2021-08-03

.devcontainer/Dockerfile, .devcontainer/devcontainer.json
Adding GitHub Codespaces to the repo
added devcontianer.json and dickerfile to the repo
Will be adding readme update as soon as PR #847 is merged (to avoid merge conflicts)
=> Enable GitHub Codespaces to Repo

azure-iot-hub/azure/iot/hub/iothub_amqp_client.py, azure-iot-hub/tests/test_iothub_amqp_client.py
Had this send messages every minute for two hours, with three successful put tokens and no issues with messages going through.
=> fix(azure-iot-hub): CBS auth for SAS tokens

azure-iot-device/samples/async-hub-scenarios/README.md, azure-iot-device/samples/sync-samples/README.md
Added recurring_telemetry.py links into the readme files
=> Danhellem recurring_telemetry.py to readme files

.github/CONTRIBUTING.md, README.md, azure-iot-device/README.md, azure-iot-device/setup.py, azure-iot-hub/README.md, azure-iot-hub/setup.py, azure-iot-nspkg/setup.py
many links in readme files are pointing to master branch
Updating links and anything the refers to `master` branch and replacing with `main`
=> [DO NOT MERGE YET] misc changes for default branch rename to main

pip_alias/README.md, pip_alias/azure-iothub-device-client/README.md, pip_alias/azure-iothub-device-client/setup.cfg, pip_alias/azure-iothub-device-client/setup.py, pip_alias/azure-iothub-service-client/README.md, pip_alias/azure-iothub-service-client/setup.cfg, pip_alias/azure-iothub-service-client/setup.py, pip_alias/iothub-client/README.md, pip_alias/iothub-client/setup.cfg, pip_alias/iothub-client/setup.py, pip_alias/iothub-service-client/README.md, pip_alias/iothub-service-client/setup.cfg, pip_alias/iothub-service-client/setup.py
Added packages using previous names that will install the current package.
=> chore: Added alias packages

azure-iot-hub/samples/get_digital_twin_sample.py, azure-iot-hub/samples/invoke_command_sample.py, azure-iot-hub/samples/invoke_component_command_sample.py, azure-iot-hub/samples/iothub_configuration_manager_sample.py, azure-iot-hub/samples/iothub_job_manager_import_export_sample.py, azure-iot-hub/samples/iothub_job_manager_method_sample.py, azure-iot-hub/samples/iothub_registry_manager_bulk_create_sample.py, azure-iot-hub/samples/iothub_registry_manager_c2d_sample.py, azure-iot-hub/samples/iothub_registry_manager_edge_device_sample.py, azure-iot-hub/samples/iothub_registry_manager_method_sample.py, azure-iot-hub/samples/iothub_registry_manager_module_method_sample.py, azure-iot-hub/samples/iothub_registry_manager_module_sample.py, azure-iot-hub/samples/iothub_registry_manager_query_sample.py, azure-iot-hub/samples/iothub_registry_manager_sample.py, azure-iot-hub/samples/iothub_registry_manager_statistics_sample.py, azure-iot-hub/samples/iothub_registry_manager_token_credential_sample.py, azure-iot-hub/samples/iothub_registry_mgr_update_x509.py, azure-iot-hub/samples/registry_manager_pnp_sample.py, azure-iot-hub/samples/update_digital_twin_sample.py
Plus some minor improvements to all the service SDK samples.
=> fix job sample for calling device methods

scripts/build-release.ps1
`bumpversion.exe` -> `bumpversion`
=> fix: release script (more)

newtsaupload.gdntsa
Spoke to Tony and might need change to iteration path.
=> Change iteration path for SDL

azure-iot-device/samples/async-hub-scenarios/provision_x509.py, azure-iot-device/samples/async-hub-scenarios/receive_message_x509.py, azure-iot-device/samples/async-hub-scenarios/send_message_via_module_x509.py, azure-iot-device/samples/async-hub-scenarios/send_message_x509.py, azure-iot-device/samples/async-hub-scenarios/upload_to_blob_x509.py, azure-iot-device/samples/sync-samples/provision_x509.py, azure-iot-device/samples/sync-samples/receive_message_x509.py, azure-iot-device/samples/sync-samples/send_message_via_module_x509.py, azure-iot-device/samples/sync-samples/send_message_x509.py, devbox_setup.md, migration_guide.md
* Added initial version of devbox_setup.py
* Changed some environment variable names
Note that a follow up PR will be necessary to fully unify and detail all environment variables in use
=> chore: Improve setup instructions

.pre-commit-config.yaml
- Updated the rev in .pre-commit-config.yaml
=> chore: Update black rev

azure-iot-device/tests/iothub/pipeline/test_pipeline_stages_iothub.py
* Several tests were incorrectly identified as "OCCURRENCE"
* Fixed a mislabeled test
=> doc (azure-iot-device): Fixed incorrect test documentation for EnsureDesiredPropertiesStage

azure-iot-device/samples/pnp/temp_controller_with_thermostats.py, azure-iot-device/tests/common/test_http_transport.py, azure-iot-device/tests/common/test_mqtt_transport.py, azure-iot-device/tests/iothub/client_fixtures.py, azure-iot-device/tests/iothub/models/test_message.py, azure-iot-device/tests/iothub/pipeline/test_pipeline_stages_iothub.py, azure-iot-device/tests/provisioning/aio/test_async_provisioning_device_client.py, azure-iot-device/tests/provisioning/conftest.py, azure-iot-device/tests/provisioning/models/test_registration_result.py, azure-iot-device/tests/provisioning/pipeline/test_mqtt_pipeline.py, azure-iot-device/tests/provisioning/pipeline/test_pipeline_stages_provisioning.py, azure-iot-device/tests/provisioning/shared_client_fixtures.py, azure-iot-device/tests/provisioning/shared_client_tests.py, azure-iot-device/tests/provisioning/test_sync_provisioning_device_client.py
* Changed various constants used in tests and samples
=> chore: removed ya fiction references

README.md
* Image link was broken - now it is not
=> fix: Addressed broken README image link

azure-iot-device/azure/iot/device/provisioning/pipeline/config.py, azure-iot-device/azure/iot/device/provisioning/pipeline/mqtt_pipeline.py, azure-iot-device/azure/iot/device/provisioning/pipeline/mqtt_topic_provisioning.py, azure-iot-device/azure/iot/device/provisioning/pipeline/pipeline_stages_provisioning_mqtt.py, devbox_setup.md, migration_guide.md, samples/README.md
- Came across these while looking into another issue
=> chore: Fix minor typos

samples/async-hub-scenarios/provision_symmetric_key_with_payload.py, samples/sync-samples/provision_symmetric_key_with_payload.py
- Removed remaining HP references from samples
=> chore: Remove remaining references

devbox_setup.md, requirements_test.txt
* Documented the environment variables necessary for local E2E
* Documented the resource setup necessary for local E2E
* Ensured that `cryptography` is installed in environment setup for testing
=> doc: Improved local E2E setup

azure-iot-device/azure/iot/device/iothub/aio/async_clients.py, azure-iot-device/azure/iot/device/iothub/sync_clients.py, tests/unit/iothub/aio/test_async_clients.py, tests/unit/iothub/shared_client_tests.py, tests/unit/iothub/test_sync_clients.py
=> fix: atomic handlers (#1060) [V3]

scripts/infra_tools/certGen.sh
=> [V3 Port - #1069] Dont use intermediate cert

.gitignore, credscan_suppression.json, v3_async_wip/tests/test_edge_hsm.py, v3_async_wip/tests/test_iothub_mqtt_client.py, v3_async_wip/tests/test_sastoken.py, v3_async_wip/tests/test_signing_mechanism.py, v3_async_wip/v3_async_wip/edge_hsm.py, v3_async_wip/v3_async_wip/iot_exceptions.py, v3_async_wip/v3_async_wip/iothub_mqtt_client.py, v3_async_wip/v3_async_wip/sastoken.py, v3_async_wip/v3_async_wip/signing_mechanism.py
* Ported sastoken.py and added typehints
* Ported edge_hsm.py and added typehints
* Ported signing_mechanism.py and added typehints
* Also ported tests for all three modules
=> [V3] Port and add type hints to auth modules

dev_utils/dev_utils/custom_mock.py, v3_async_wip/tests/test_iothub_mqtt_client.py, v3_async_wip/v3_async_wip/iothub_mqtt_client.py
* Formalized incoming data generators as properties and refactored implementation
* Formalized C2D messages as being Device exclusive
* Added suppression for errors in incoming data generators
* Added suppression for errors in background tasks
* Added robust error handling tests for those generators and tasks
=> [V3] Generator and background task exception handling

migration_guide.md
device_client needs to be changed to client in this case.
- **Found a bug?** Please help us fix it by thoroughly documenting it and filing an issue on GitHub (See …
=> Fix typo: device_client has never been initialized

samples/iothub_simple_telemetry.py
Tutorial located here:
https://learn.microsoft.com/en-us/azure/iot-develop/quickstart-send-telemetry-iot-hub?pivots=programming-language-python
Which has an open PR to list one of the new samples being used. This sample will also likely be updated, so we want to keep track of what's being used where.
=> Notates sample being used in tutorial

README.md, migration_guide_iothub.md, migration_guide_provisioning.md
* Addressed bugbash feedback on docs
=> fix: documentation errors

dev_utils/dev_utils/service_helper_sync.py, samples/pnp/simple_thermostat.py
Fixed incorrect type checking logic flagged by flake8
=> Static analysis typecheck fixes
